### ISSUE TITLE
How to Load STL geometry into Mesh geometry component?

### ISSUE THREAD

**Issue by mike-diff** [vatro/svelthree#33]
I am trying to load an STL file into the example scene using STLLoader.
``` html
<script>
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js'

let loader = new STLLoader();
	
let stlFile = loader.load("./3DBenchy.stl", function (geometry) {
    console.log(geometry) // logs an object type BufferGeometry
    return geometry
});
</script>

...
<Mesh
  {scene}
  geometry={stlFile}
  material={cubeMaterial}
  mat={{ roughness: 0.5, metalness: 0.5, color: 0xff3e00 }}
  pos={[0, 0, 0]}
  rot={[0, 0, 0]}
  castShadow
  receiveShadow />

...
```
Errors
``` js
- SVELTHREE > Mesh : mesh was not created!
- Uncaught TypeError: object3DUtils is undefined
```

Can someone show me an example of the correct way to do this?

**Comment by vatro** [comment]
Hi! :)

Loaders are still a TODO, see: #15 
I'll take a closer look at the issue and give more feedback concerning these use cases.

**Comment by vatro** [comment]
> I'll take a closer look at the issue and give more feedback concerning these use cases.

**Good news**! Turns out my initial feedback (see [comment](https://github.com/vatro/svelthree/issues/33#issuecomment-722634467) history) was false, and this **IS possible**, which is also great because it means Loaders can generally be used vanilla style (no need for wrapping them as components), though **beware**: importing from `three/examples/jsm` folder will also import a complete (additional) three module blowing up your bundle (no tree shaking), this is a known issue, that's why svelthree is embedding [svelthree-three](https://github.com/vatro/svelthree-three).

The problem with your example is that you have to make sure the geometry is available when the Mesh component mounts, so a simple quickfix would be:

```svelte
<script>
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js'

let loader = new STLLoader();

let stlGeom // undefined
	
let stlFile = loader.load("./3DBenchy.stl", function (geometry) {
    console.log(geometry) // logs an object type BufferGeometry
    //return geometry
    stlGeom = geometry
});

</script>

...
{#if stlGeom}
<Mesh
  {scene}
  geometry={stlGeom}
  material={cubeMaterial}
  mat={{ roughness: 0.5, metalness: 0.5, color: 0xff3e00 }}
  pos={[0, 0, 0]}
  rot={[0, 0, 0]}
  castShadow
  receiveShadow />
{/if}

...
```
I've tested it, but let me know if it worked for you too!

**Comment by mike-diff** [comment]
@vatro thanks man this did the trick!
<img width="525" alt="Screen Shot 2020-11-05 at 5 22 38 PM" src="https://user-images.githubusercontent.com/29803478/98314799-9d01fb00-1f8b-11eb-9a7b-a1d6f4e4a5f3.png">

This solved my issue and now I can move forward with testing things. Really cool thing you have made here.

**Comment by vatro** [comment]
> This solved my issue and now I can move forward with testing things. Really cool thing you have made here.

Glad to hear that! Thank you! 😁
